from sqlalchemy import Column, String, Integer, DateTime, LargeBinary, Date
from .base import Base


class Application(Base):
    __tablename__ = "Applications"

    # Primary key generated by API, e.g., AP0001
    ApplicationID = Column(String(20), primary_key=True, index=True)

    # Core applicant fields
    FullName = Column(String(255), nullable=False)
    Email = Column(String(255), nullable=False)
    LinkedInURL = Column(String(512), nullable=True)
    WebsitePortfolio = Column(String(512), nullable=True)
    Phone = Column(String(50), nullable=True)

    # Meta fields
    ServingDays = Column(Integer, nullable=True)
    SubmissionDate = Column(DateTime, nullable=True)
    HasExperience = Column(String(10), nullable=True)  # stores "Yes"/"No"
    NoticePeriod = Column(Integer, nullable=True)
    LastWorkingDay = Column(Date, nullable=True)
    CurrentLocation = Column(String(255), nullable=True)
    PreferredLocation = Column(String(255), nullable=True)

    # Resume blob
    Resume = Column(LargeBinary, nullable=True)
